# Generated by Django 2.2.9 on 2020-09-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0005_auto_20200829_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.TextField(),
        ),
    ]
