# Generated by Django 2.2.9 on 2020-09-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0006_auto_20200903_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
